---
default_install_hook_types:
  - commit-msg
  - post-checkout
  - post-commit
  - post-merge
  - post-rewrite
  - pre-commit
  - pre-merge-commit
  - pre-push
  - pre-rebase
  - prepare-commit-msg
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.12.0
    hooks:
      - id: commitizen
        name: "Single commit message validation"
        stages: [commit-msg]
      - id: commitizen-branch
        name: "Branch commit messages validation"
        stages: [pre-push]
