[package]
name = "hooks"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "=0.4.33"
thiserror = "=1.0.56"

[dependencies.mysql_async]
features = [
    "derive", "native-tls", "binlog", "tokio-native-tls", "default-rustls",
    "rustls", "tokio-rustls", "webpki", "webpki-roots", "tracing",
    "rustls-pemfile"
]
version = "=0.33.0"

[dependencies.postgres]
features = [
    "with-smol_str-01", "with-uuid-0_8", "array-impls", "with-time-0_3",
    "with-geo-types-0_6", "with-geo-types-0_7", "with-eui48-0_4",
    "with-chrono-0_4", "with-serde_json-1", "with-eui48-1", "with-bit-vec-0_6",
    "with-time-0_2", "with-uuid-1"
]
version = "=0.19.7"

[dependencies.postgres-types]
features = [
    "with-serde_json-1", "array-init", "with-uuid-0_8", "cidr-02",
    "with-geo-types-0_6", "with-cidr-0_2", "serde_json-1", "chrono-04",
    "postgres-derive", "time-03", "with-time-0_3", "bit-vec-06", "time-02",
    "eui48-04", "with-smol_str-01", "uuid-08", "smol_str-01", "derive",
    "serde-1", "with-bit-vec-0_6", "with-eui48-0_4", "with-geo-types-0_7",
    "with-uuid-1", "eui48-1", "with-time-0_2", "array-impls", "with-eui48-1",
    "with-chrono-0_4", "uuid-1", "geo-types-0_7", "geo-types-06"
]
version = "=0.2.6"

[dependencies.serde]
features = ["derive"]
version = "=1.0.196"

[dependencies.tokio-postgres]
features = [
    "runtime", "with-bit-vec-0_6", "with-time-0_3", "with-time-0_2",
    "with-uuid-1", "with-eui48-1", "with-uuid-0_8", "with-geo-types-0_7",
    "js", "with-geo-types-0_6", "with-eui48-0_4", "array-impls",
    "with-serde_json-1", "with-chrono-0_4", "with-smol_str-01"
]
version = "=0.7.10"

[dev-dependencies]
test-case = "=3.3.1"
pretty_assertions = "=1.4.0"
