[package]
name = "hooks"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "=0.4.33"
thiserror = "=1.0.56"

[dependencies.serde]
features = ["derive"]
version = "=1.0.196"

[dev-dependencies]
test-case = "=3.3.1"
pretty_assertions = "=1.4.0"
