refresh_rate: 5 seconds

appenders:
  console:
    kind: console
    encoder:
      pattern: "{d} [{t}] {h({l})} {M}: {m}{n}"
  file:
    kind: file
    path: info.log
    encoder:
      pattern: "{d} [{t}] {l} {M}: {m}{n}"

root:
  appenders:
    - console

loggers:
  multi_logger_config::a:
    level: info
    appenders:
      - file
    additive: true
