---
name: Commit Message Validation

"on":
  pull_request:

jobs:
  validate-commits:
    runs-on: ubuntu-latest

    steps:
      # Checkout at the last commit of the branch to be merged
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '>3.11'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install

      # Validate commit messages between the base branch and the last commit of
      # the branch to be merged
      - name: Validate Commit Messages
        if: github.event_name == 'pull_request'
        run: |
          poetry run cz check --rev-range \
          ${{ github.event.pull_request.base.sha }}..\
          ${{ github.event.pull_request.head.sha }}
