---
name: Commit Message Validation

"on":
  pull_request:

jobs:
  validate-commits:
    runs-on: ubuntu-latest

    steps:
      # Checkout at the last commit of the branch to be merged
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      # Run commit message validation workflow
      - name: Validate commit messages
        uses: ./github-actions/commit-message-validation
