---
name: 'Github Jira Integration'

on:
  release: # Trigger the workflow on release
    types: [created]

jobs:
  jira_release:
    name: 'Create Jira Release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Install poetry'
        run: pipx install poetry

      - name: 'Setup Python with Poetry'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: 'Install dependencies'
        run: poetry install

      - name: 'Echo event information'
        run: |
          echo ${{ github.event }}

      - name: 'Echo event JSON information'
        run: |
          echo ${{ toJson(github.event) }}

