---
name: Release project

"on":
  # Since the repository is public, there are no concerns regarding CI usage.
  push:
    tags:
      - "v*"

# Concurrency serves to prevent simultaneous execution of multiple identical
# workflows in the same branch.
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  release:
    name: Release project
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            target: "x86_64-unknown-linux-gnu"
          - os: ubuntu-20.04
            target: "x86_64-unknown-linux-gnu"
          - os: windows-2022
            target: "x86_64-pc-windows-msvc"
          - os: macos-13
            target: "x86_64-apple-darwin"
          - os: macos-14
            target: "aarch64-apple-darwin"

    runs-on: ${{ matrix.os }}
    steps:
      # Checkout the code base.
      - name: Checkout code
        uses: actions/checkout@v4

      # Extract the Rust channel from the 'rust-toolchain.toml' file.
      - name: Extract Rust Channel
        shell: bash
        id: toolchain
        run: ./scripts/extract_rust_channel.sh

      # Install the toolchain.
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.toolchain.outputs.version }}
          targets: ${{ matrix.target }}

      # Retrieve the dependencies from the cache.
      - name: Cache dependencies
        id: cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: rust-${{ matrix.os }}-${{ matrix.target }}-
          shared-key: test
          cache-targets: true
          cache-all-crates: true
          # The 'generate-caches.yaml' workflow is responsible for caching the
          # dependencies.
          save-if: false

      - name: Run build for the release profile
        shell: bash
        run: |
          cargo build \
            --release \
            --all-targets \
            --target ${{ matrix.target }}

# TODO(future): Add a step to create a release on GitHub with the artifacts.
...
